### ISSUE TITLE
Incomplete `params` handling in Api::V1::KeywordsController

### ISSUE THREAD

**Issue by abhinavmsra** [m-rwash/google-scraping#1]
In `#search_keyword, #search_adwords_urls , #search_all_urls ` , following conditional is used:

```
if params.present? && params[:term].present?
   respond_with ....
end
```

What happens if `params[:term]` is not present?

**Comment by m-rwash** [comment]
It won't respond at all, it will face no content issue. This terrible mistake, I've completely forgotten to provide else statement.
