### ISSUE TITLE
Invest time in learning proper debugging tools as it will save you tons of time

### ISSUE THREAD

**Issue by olivierobert** [m-rwash/google-scraping#6]
Debugging on the page has limits:

![googlescraping](https://user-images.githubusercontent.com/696529/34552327-5b1c39b2-f153-11e7-9c46-a375cc2d25c1.png)

So learn tools like [pry](https://github.com/pry/pry/wiki/Runtime-invocation)

**Comment by m-rwash** [comment]
I do use pry, I just use both
